With NGSInventory as 
(SELECT 
	INVENTDIMID
	,INVENTTRANSID
FROM SAG_InventTransStaging
WHERE DATAAREAID IN ('NGS1', 'NNL2')
	AND (STATUSISSUE IN ('1', '3')
		OR (STATUSRECEIPT LIKE '1' AND INVOICERETURNED = 1)) -- added to capture returns 
GROUP BY INVENTDIMID
	,INVENTTRANSID)