-- Databricks notebook source
-- MAGIC %python
-- MAGIC import os
-- MAGIC
-- MAGIC ENVIRONMENT = os.environ["__ENVIRONMENT__"]

-- COMMAND ----------

-- MAGIC %md
-- MAGIC The target catalog depens on the enivronment. Since we are using Unity Catalog we need to use a unqiue name for the catalog. This is the reason why we name the dev silver catalog "silver_dev" for example.

-- COMMAND ----------

-- MAGIC %python
-- MAGIC spark.catalog.setCurrentCatalog(f"gold_{ENVIRONMENT}")

-- COMMAND ----------

CREATE SCHEMA if not EXISTS orion

-- COMMAND ----------

USE SCHEMA orion

-- COMMAND ----------
CREATE OR REPLACE TABLE dim_sales_document 
 (
  sales_document_pk BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  document_id STRING NOT NULL COMMENT 'The unique id of the document within country',
  document_date DATE COMMENT 'The date of the document',
  document_source STRING COMMENT 'The document source - credit memo, msp, quote, sales order, etc..',
  country_code STRING COMMENT 'The country code of the document',
  source_system_id BIGINT COMMENT 'The ID from the Source System Dimension',
  bill_to_customer_no string COMMENT '',
  biztalkguid string COMMENT '',
  credit_memo  string COMMENT '',
  currency_code  string COMMENT '',
  currency_factor  decimal(10,4) COMMENT '',
  cust_gen_bus_postinggroup   string COMMENT '',
  cust_vatbus_postinggroup  string COMMENT '',
  customer_no string COMMENT '',
  dimension_set_id  string COMMENT '',
  doucment_type  int COMMENT '',
  due_date   timestamp COMMENT '',
  invoicebiztalkguid  string COMMENT '',
  invoice_title  string COMMENT '',
  mspusagesheaderbiztalkguid  string COMMENT '',
  order_date timestamp COMMENT '',
  order_no  string COMMENT '',
  posting_date timestamp COMMENT '',
  process_code   string COMMENT '',
  sales_credit_memo_no  string COMMENT '',
  sales_invoice_no string COMMENT '',
  sell_to_customer_no  string COMMENT '',
  shortcut_dimension1_code  string COMMENT '',
  sid bigint COMMENT '',
  vendor_dimension_value  string COMMENT '',
  vendor_reference   string COMMENT '',
  version_no  int COMMENT '',
  start_datetime TIMESTAMP NOT NULL COMMENT 'The dimensional start date of the record',
  end_datetime TIMESTAMP COMMENT 'The dimensional end date of the record, those records with a NULL value are current',
  is_current INT COMMENT 'Flag to indicate if this is the active dimension record per code',
  Sys_Gold_InsertedDateTime_UTC TIMESTAMP COMMENT 'The timestamp when this record was inserted into gold',
  Sys_Gold_ModifiedDateTime_UTC TIMESTAMP COMMENT 'The timestamp when this record was last updated in gold',
  CONSTRAINT `dim_sales_document_primary_key` PRIMARY KEY (`sales_document_pk`))
USING delta
CLUSTER BY (source_system_id,document_id)
TBLPROPERTIES (
  'delta.checkpointPolicy' = 'v2',
  'delta.constraints.datewithinrange_start_datetime' = 'start_datetime >= \'1900-01-01\'',
  'delta.constraints.valid_is_current_value' = 'is_current IN ( 1 , 0 )',
  'delta.enableDeletionVectors' = 'true',
  'delta.enableRowTracking' = 'true',
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.feature.checkConstraints' = 'supported',
  'delta.feature.columnMapping' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.identityColumns' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.feature.rowTracking' = 'supported',
  'delta.feature.v2Checkpoint' = 'supported')
;
-- COMMAND ----------

ALTER TABLE dim_sales_document ADD CONSTRAINT dateWithinRange_Bronze_InsertDateTime CHECK (Sys_Gold_InsertDateTime_UTC >= '1900-01-01');
ALTER TABLE dim_sales_document ADD CONSTRAINT dateWithinRange_Silver_InsertDateTime CHECK (Sys_Gold_ModifedDateTime_UTC >= '1900-01-01');
