# Databricks notebook source
# Importing Libraries
import os

# COMMAND ----------

ENVIRONMENT = os.environ["__ENVIRONMENT__"]
ENVIRONMENT

# COMMAND ----------


spark.catalog.setCurrentCatalog(f"gold_{ENVIRONMENT}")


# COMMAND ----------

catalog = spark.catalog.currentCatalog()
schema = 'orion'

# COMMAND ----------

# REMOVE ONCE SOLUTION IS LIVE
if ENVIRONMENT == 'dev':
    spark.sql(f"""
              DROP TABLE IF EXISTS {catalog}.{schema}.fact_sales_transaction
              """)

# COMMAND ----------

spark.sql(f"""
CREATE OR REPLACE TABLE {catalog}.{schema}.fact_sales_transaction (
  sales_transaction_pk BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  purchase_currency_fk bigint,
  sales_document_fk int,
  entity_fk bigint,
  product_fk bigint,
  reseller_fk bigint,
  source_system_fk bigint,
  vendor_fk bigint,
  posting_date_fk int,
biztalk_guid string comment '',
cogs_account_no string comment '',
description string comment '',
doc_no_occurrence int comment '',
gen_bus_postinggroup string comment '',
line_no int comment '',
order_line_no int comment '',
sales_credit_memo_line_no string comment '',
sales_invoice_line_no string comment '',
sales_account_no string comment '',
item_global_dimension1_code string comment '',
resource_global_dimension1_code string comment '',
item_dimension1_code string comment '',
sid bigint comment '',
sys_databasename string comment '',
sys_rownumber bigint comment '',
type int comment '',
vatprod_postinggroup string comment '',
amount_local_currency decimal(10,2) comment '',
amount_EUR decimal(10,2) comment '',
amount_including_vat_local_currency decimal(10,2) comment '',
amount_including_vat_EUR decimal(10,2) comment '',
cost_amount_local_currency decimal(10,2) comment '',
cost_amount_EUR decimal(10,2) comment '',
quantity decimal(10,2) comment '',
total_cost_purchase_currency decimal(10,2) comment '',
total_cost_EUR decimal(10,2) comment '',
unit_cost_local_currency decimal(10,2) comment '',
unit_cost_purchase_currency decimal(10,2) comment '',
unit_cost_EUR decimal(10,2) comment '',
unit_price decimal(10,2) comment '',
  Sys_Gold_InsertedDateTime_UTC TIMESTAMP COMMENT 'The timestamp when this record was inserted into gold',
  Sys_Gold_ModifiedDateTime_UTC TIMESTAMP COMMENT 'The timestamp when this record was last updated in gold',
  CONSTRAINT `sales_transaction_primary_key` PRIMARY KEY (`sales_transaction_pk`))
USING delta
CLUSTER BY (source_system_fk,sales_document_fk, entity_fk, product_fk)
TBLPROPERTIES (
  'delta.checkpointPolicy' = 'v2',
  'delta.enableDeletionVectors' = 'true',
  'delta.enableRowTracking' = 'true',
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.feature.checkConstraints' = 'supported',
  'delta.feature.columnMapping' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.identityColumns' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.feature.rowTracking' = 'supported',
  'delta.feature.v2Checkpoint' = 'supported')
""")
