# Databricks notebook source
# Importing Libraries
import os
spark = spark  # noqa

# COMMAND ----------

ENVIRONMENT = os.environ["__ENVIRONMENT__"]
ENVIRONMENT

# COMMAND ----------


spark.catalog.setCurrentCatalog(f"gold_{ENVIRONMENT}")


# COMMAND ----------

catalog = spark.catalog.currentCatalog()
schema = 'orion'

# COMMAND ----------

# REMOVE ONCE SOLUTION IS LIVE
if ENVIRONMENT == 'dev':
    spark.sql(f"""
              DROP TABLE IF EXISTS {catalog}.{schema}.dim_entity
              """)

# COMMAND ----------

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.dim_entity (
  entity_pk BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  entity_code STRING NOT NULL COMMENT 'The Entity code',
  entity_code_legacy STRING COMMENT 'The old legacy Entity code',
  entity_description STRING COMMENT 'A description of the entity',
  entity_type STRING COMMENT 'Entity type code',
  legal_headquarters STRING COMMENT 'The legal headquarters',
  administrative_city STRING COMMENT 'The city where the entity resides',
  date_established STRING COMMENT 'Date the entity was established',
  entity_local_currency STRING COMMENT 'Entity local currency code',
  start_datetime TIMESTAMP NOT NULL COMMENT 'The dimensional start date of the record',
  end_datetime TIMESTAMP COMMENT 'The dimensional end date of the record, those records with a NULL value are current',
  is_current INT COMMENT 'Flag to indicate if this is the active dimension record per code',
  Sys_Gold_InsertedDateTime_UTC TIMESTAMP COMMENT 'The timestamp when this record was inserted into gold',
  Sys_Gold_ModifiedDateTime_UTC TIMESTAMP COMMENT 'The timestamp when this record was last updated in gold',
  CONSTRAINT `entity_primary_key` PRIMARY KEY (`entity_pk`))
USING delta
CLUSTER BY (entity_code)
TBLPROPERTIES (
  'delta.checkpointPolicy' = 'v2',
  'delta.constraints.datewithinrange_start_datetime' = 'start_datetime >= "1900-01-01"',
  'delta.constraints.valid_is_current_value' = 'is_current IN ( 1 , 0 )',
  'delta.enableDeletionVectors' = 'true',
  'delta.enableRowTracking' = 'true',
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.feature.checkConstraints' = 'supported',
  'delta.feature.columnMapping' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.identityColumns' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.feature.rowTracking' = 'supported',
  'delta.feature.v2Checkpoint' = 'supported')
""")

# COMMAND ----------

# Add in the UNKNOWN Member
sqldf= spark.sql(f"""
SELECT CAST(-1 AS BIGINT) AS entity_pk,
       CAST('N/A' AS STRING) AS entity_code,
       CAST(NULL AS STRING) AS entity_code_legacy,
       CAST(NULL AS STRING) AS entity_description,
       CAST(NULL AS STRING) AS entity_type,
       CAST(NULL AS STRING) AS legal_headquarters,
       CAST(NULL AS STRING) AS administrative_city,
       CAST(NULL AS STRING) AS date_established,
       CAST(NULL AS STRING) AS entity_local_currency,
       CAST('1900-01-01' AS TIMESTAMP) AS start_datetime,
       CAST(NULL AS TIMESTAMP) AS end_datetime,
       CAST(1 AS INTEGER) AS is_current,
       CAST(NULL AS TIMESTAMP) AS Sys_Gold_InsertedDateTime_UTC,
       CAST(NULL AS TIMESTAMP) AS Sys_Gold_ModifiedDateTime_UTC
FROM {catalog}.{schema}.dim_entity 
WHERE NOT EXISTS (SELECT 1 FROM {catalog}.{schema}.dim_entity WHERE entity_pk = -1)
""").write.mode("append").option("mergeSchema", "true").saveAsTable(f"{catalog}.{schema}.dim_entity")