# Databricks notebook source

# Importing Libraries
import os
# COMMAND ----------
ENVIRONMENT = os.environ["__ENVIRONMENT__"]
ENVIRONMENT
# COMMAND ----------


spark.catalog.setCurrentCatalog(f"gold_{ENVIRONMENT}")


# COMMAND ---------- 

catalog = spark.catalog.currentCatalog()
schema = 'orion'
# COMMAND ----------

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {catalog}.{schema}.sales_document (
  sales_document_pk BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  document_id STRING NOT NULL COMMENT 'The unique id of the document within country',
  document_date DATE COMMENT 'The date of the document',
  document_source STRING COMMENT 'The document source - credit memo, msp, quote, sales order, etc..',
  country_code STRING COMMENT 'The country code of the document',
  source_system_id BIGINT COMMENT 'The ID from the Source System Dimension',
  bill_to_customer_no STRING COMMENT '',
  biztalkguid STRING COMMENT '',
  credit_memo STRING COMMENT '',
  currency_code STRING COMMENT '',
  currency_factor DECIMAL(10,4) COMMENT '',
  cust_gen_bus_postinggroup STRING COMMENT '',
  cust_vatbus_postinggroup STRING COMMENT '',
  customer_no STRING COMMENT '',
  dimension_set_id STRING COMMENT '',
  doucment_type INT COMMENT '',
  due_date TIMESTAMP COMMENT '',
  invoicebiztalkguid STRING COMMENT '',
  invoice_title STRING COMMENT '',
  mspusagesheaderbiztalkguid STRING COMMENT '',
  order_date TIMESTAMP COMMENT '',
  order_no STRING COMMENT '',
  posting_date TIMESTAMP COMMENT '',
  process_code STRING COMMENT '',
  sales_credit_memo_no STRING COMMENT '',
  sales_invoice_no STRING COMMENT '',
  sell_to_customer_no STRING COMMENT '',
  shortcut_dimension1_code STRING COMMENT '',
  sid BIGINT COMMENT '',
  vendor_dimension_value STRING COMMENT '',
  vendor_reference STRING COMMENT '',
  version_no INT COMMENT '',
  start_datetime TIMESTAMP NOT NULL COMMENT 'The dimensional start date of the record',
  end_datetime TIMESTAMP COMMENT 'The dimensional end date of the record, those records with a NULL value are current',
  is_current INT COMMENT 'Flag to indicate if this is the active dimension record per code',
  Sys_Gold_InsertedDateTime_UTC TIMESTAMP COMMENT 'The timestamp when this record was inserted into gold',
  Sys_Gold_ModifiedDateTime_UTC TIMESTAMP COMMENT 'The timestamp when this record was last updated in gold',
  CONSTRAINT `sales_document_primary_key` PRIMARY KEY (`sales_document_pk`))
USING delta
CLUSTER BY (document_id)
TBLPROPERTIES (
  'delta.checkpointPolicy' = 'v2',
  'delta.constraints.datewithinrange_start_datetime' = 'start_datetime >= "1900-01-01"',
  'delta.constraints.valid_is_current_value' = 'is_current IN ( 1 , 0 )',
  'delta.enableDeletionVectors' = 'true',
  'delta.enableRowTracking' = 'true',
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.feature.checkConstraints' = 'supported',
  'delta.feature.columnMapping' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.identityColumns' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.feature.rowTracking' = 'supported',
  'delta.feature.v2Checkpoint' = 'supported')
""")