with ExchangeRates as 
(
SELECT 
	CONVERT(DATE, STARTDATE) AS StartDate
	,TOCURRENCY
	,FROMCURRENCY
	,RATE
FROM ExchangeRateEntityStaging 
	WHERE CONVERT(DATE, STARTDATE) BETWEEN @from AND @to 
	AND (FROMCURRENCY = 'GBP' AND TOCURRENCY = 'EUR')
)