
trigger:
- none

pool:
  vmImage: ubuntu-latest
  

steps:
- checkout: self
  path: main
  clean: false
- checkout: git://Group IT Program/inf-edw@adf_publish
  path: adf_publish




- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'SC-ARM-EDW-UAT'
    subscriptionId: 'bf75b24f-2b10-4ada-a25a-b5bec3311486'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-ig-lakehouse-uat-westeurope'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '../adf_publish/adf-ig-dev-westeurope/ARMTemplateForFactory.json'
    csmParametersFile: '../adf_publish/adf-ig-dev-westeurope/ARMTemplateParametersForFactory.json'
    overrideParameters: '-factoryName "adf-ig-uat-westeurope"'
    deploymentMode: 'Incremental'