trigger:
  batch: true
  branches:
    include:
      - production
  paths:
    include:
      - databricks
      - deployment
    exclude:
      - README.md
      - deployment/images
      - deployment/pipelines/templates
      - deployment/pipelines/pl_adf_uat.yml
      - deployment/pipelines/pl_adf_prod.yml
      - deployment/pipelines/ci.yml

variables:
- group: vg-inf-edw-deployment

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  path: main
  clean: false

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'SC-ARM-EDW-PROD'
    ScriptType: 'FilePath'
    ScriptPath: '../main/deployment/scripts/ps_db_update_repo.ps1'
    ScriptArguments: '-AzureDevOpsBranch $(v-prod-branch) -Token $(v-prod-token) -DatabricksRepoURI $(v-prod-databricks-repo-uri)'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true