
trigger:
- none

pool:
  vmImage: ubuntu-latest
  

steps:
- checkout: self
  path: main
  clean: false
- checkout: git://Group IT Program/inf-edw@adf_publish
  path: adf_publish




- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'SC-ARM-EDW-PROD'
    subscriptionId: '4b6b9329-18aa-4bf0-83f2-090c052e7fd3'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-ig-lakehouse-prod-westeurope'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '../adf_publish/adf-ig-dev-westeurope/ARMTemplateForFactory.json'
    csmParametersFile: '../adf_publish/adf-ig-dev-westeurope/ARMTemplateParametersForFactory.json'
    overrideParameters: '-factoryName "adf-ig-prod-westeurope"'
    deploymentMode: 'Incremental'