trigger:
  batch: true
  branches:
    include:
      - testing
  paths:
    include:
      - databricks
      - deployment
    exclude:
      - README.md
      - deployment/images
      - deployment/pipelines/templates
      - deployment/pipelines/pl_adf_uat.yml
      - deployment/pipelines/pl_adf_prod.yml
      - deployment/pipelines/ci.yml

variables:
  - group: vg-inf-edw-deployment
  - group: inf-edw-uat

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    path: main
    clean: false

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'SC-ARM-EDW-UAT'
      ScriptType: 'FilePath'
      ScriptPath: '../main/deployment/scripts/ps_db_update_repo.ps1'
      ScriptArguments: '-AzureDevOpsBranch testing -Token $(databricks-bearer-token) -DatabricksRepoURI $(v-uat-databricks-repo-uri)'
      azurePowerShellVersion: 'LatestVersion'
      pwsh: true
