# Databricks notebook source

dbutils.widgets.text('catalog', '')
catalog = dbutils.widgets.get('catalog')

spark.sql(
    f"""
        CREATE TABLE IF NOT EXISTS {catalog}.dojo_metadata.meta_audience_info (
            audience_id BIGINT COMMENT "The ID generated by this audience.",
            audience_name VARCHAR(50) COMMENT "The name of the custom audience.",
            campaign_id INT COMMENT "Identifier for the Facebook ad campaign",
            pixel_id VARCHAR(50) COMMENT "Facebook pixel identifier for tracking conversions.",
            featured_products ARRAY<INT> COMMENT "List of featured products used in campaign.",
            wider_brand ARRAY<INT> COMMENT "List of products in wider brand.",
            super_brands ARRAY<STRING> COMMENT "List of brands used in campaign.",
            campaign_start DATE COMMENT "The date the campaign started.",
            campaign_end DATE COMMENT "The date the campaign ended",

            CONSTRAINT meta_audiences_pk PRIMARY KEY (audience_id)
        )
        COMMENT "This table contains information for tracking the audience segments used in Facebook ad campaigns, including the audience names, their corresponding audience IDs (generated by Meta), campaign IDs, the brands and products featured in the campaign, and the campaign start and end dates."
        TBLPROPERTIES (
            delta.enableChangeDataFeed = true,
            delta.columnMapping.mode = 'name',
            table_schema.version = 1
        )
    """
)

spark.sql(f"ALTER TABLE {catalog}.dojo_metadata.meta_audience_info SET OWNER TO dojo_auto")
